### ISSUE TITLE
It doesn’t work.

### ISSUE THREAD

**Issue by braydenbower** [tom2238/apt-encoder#1]
Hi, 

I downloaded and compiled the software but when running it, I can broadcast tga-> apt signals but when trying to decode them, they are just completely screwed up and none of the image is there. When running, the app makes a very odd sound and doesn’t have a constant beep.

**Comment by tom2238** [comment]
Hi,

What are the program parameters? Is the picture completely black? Is it possible to send a piece of audio file? I use WxToImg for decoding. Maybe bad volume or sampling frequency in WxToImg.
