### ISSUE TITLE
Decoder

### ISSUE THREAD

**Issue by ByteHD** [tom2238/apt-encoder#3]
Hey, thank you for your great work!

Which decoder do you use to get the rgb image back? can you send me a link?
Wxtoimg only gives me black and white

**Comment by tom2238** [comment]
Hi.
First decode image in WxToImg (disable gamma correction). Save images from channel A and B separately (909px width per each image) without sync and telemetry. Select TGA format. 
Next compile apt-colorm.c with ./apt-colorm.make
Next run ./apt-colorm -a channelA.tga -b channelB.tga -o colorimage.tga
See results

**Comment by ByteHD** [comment]
Thank you!
