### ISSUE TITLE
noaa_apt.mk points to author's system

### ISSUE THREAD

**Issue by comicsansgreenki** [tom2238/apt-encoder#4]
Title says it all. Fixed-up file is on my Gdrive [right here](https://drive.google.com/file/d/10YtV4fQSy6l4c6PGBlIwiTkp-hNkqfxo/view?usp=drivesdk).

On the plus side, this compiled successfully on Termux (latest),  with a dependency of 'clang'.

**Comment by tom2238** [comment]
Hi.
I have a idea switch to the QtCreator IDE (qmake or cmake).  I use it for all my small hobby C projects (including Arduino).

**Comment by comicsansgreenki** [comment]
And I'm dumb. Forgot about pull requests, like the noob I am >_<

**Comment by tom2238** [comment]
No problem Ben.
