### ISSUE TITLE
Can someone explain how to build this on windows or raspberry pi?

### ISSUE THREAD

**Issue by Marleu** [tom2238/apt-encoder#5]

**Comment by Marleu** [comment]
pi@pi4:~/aptmake/apt-encoder $ sudo make
----------Sestavování projektu:[ noaa_apt - Debug ]----------
make[1]: Entering directory '/home/pi/aptmake/apt-encoder'
gcc -c  "./main.c" -O3 -Wall  -o ./Debug/main.c.o -I. -I.
In file included from ./main.c:1:
./main.h:16:10: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [noaa_apt.mk:95: Debug/main.c.o] Error 1
make[1]: Leaving directory '/home/pi/aptmake/apt-encoder'
make: *** [Makefile:5: All] Error 2

**Comment by Marleu** [comment]
nvm... i was being dumb

**Comment by tom2238** [comment]
Hi.
Try install readline library and development files.

**Comment by Oscilloscopy** [comment]
> Hi. Try install readline library and development files.

Ok but how do you compile it? Aren't those just reqs for it?

**Comment by tom2238** [comment]
QtCreator IDE is used to compile (qmake). Used libraries: pthread; m; readline; termcap;.
